##    SECURITY
#security:
#  user: root
#    password: rootroot




#   DATABASE
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fakebook
    username: root
    password: rootroot

  jpa:
    generate-ddl: true
    show-sql: false
#    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active: mysql

  session:
    store-type: jdbc

  mail:
    host: smtp.gmail.com
    username: fakebook.webapp@gmail.com
    password: CrltKOct17
    port: 587
    protocol: smtp

# TODO: wrote classpath:/static/js or css rather than classpath:/resources/static/js
# TODO: below and in application.yml. fixed it. commented both to see which one actually worked
# TODO: this or static locations in application.yml. but it still worked without either
#  resources:
#    static-locations:
#    - classpath:/static/js/
#    - classpath:/static/css/



# mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp
  thymeleaf:
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false


# reroutes all controllers from localhost:8080/users/all           or    localhost:8080/posts/all
# to                            localhost:8080/fakebook/users/all  or    localhost:8080/fakebook/posts/all
server:
  context-path: /fakebook
  port: 8080






